# -*- coding: utf-8 -*-
"""print_example

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jEEYHWgemJEZRaRtPuZiLvBWNj7ULYZd
"""

# 02.16.2020
# Code up 100 questions

#6 Output special chracter
print("\"!@#$%^&*()\"")

#7 Output path of Window operating system
print("\"C:\\Download\\hello.cpp\"")

