# -*- coding: utf-8 -*-
"""print_example

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jEEYHWgemJEZRaRtPuZiLvBWNj7ULYZd
"""

# 02.16.2020
# Code up 100 questions

#6 Output special chracter
print("\"!@#$%^&*()\"")

#7 Output path of Window operating system
print("\"C:\\Download\\hello.cpp\"")

#7 Output speacial chracters using unicode
# When I use a unicode or hanguel, have to use below code
# import io, sys
# sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf8')

print("\u250C\u252C\u2510")
print("\u251C\u253C\u2524")
print("\u2514\u2534\u2518")